# NomadNet Configuration Template
# Auspiciado por Cipropanama.org - https://cipropanama.org

[nomadnet]
display_name = CiproPanama-Emergencia-01
enable_node = yes
enable_microweb = yes
pages_path = /var/nomadnet/pages
enable_propagation_node = yes

[logging]
loglevel = 4
