# Reticulum Network Stack Configuration Template
# Auspiciado por Cipropanama.org - https://cipropanama.org

[reticulum]
enable_transport = yes
share_instance = yes
shared_instance_port = 37428
instance_control_port = 37429
panic_on_interface_error = no

[logging]
loglevel = 4

[interfaces]
  [[Auto Local Interface]]
    type = AutoInterface
    enabled = yes
    mode = full

  # Interfaz RNode LoRa (Descomentar o configurar mediante rns-admin)
  # [[RNode LoRa]]
  #   type = RNodeInterface
  #   enabled = yes
  #   port = /dev/ttyUSB0
  #   frequency = 915000000
  #   bandwidth = 125000
  #   txpower = 17
  #   spreadingfactor = 8
  #   codingrate = 5
  #   flow_control = false

  # Interfaz Módem KISS TNC / Packet Radio
  # [[KISS Modem]]
  #   type = KISSInterface
  #   enabled = no
  #   port = /dev/ttyUSB1
  #   speed = 115200

  # Servidor TCP Local (Para conexiones LAN / WiFi)
  [[TCP Server Interface]]
    type = TCPServerInterface
    enabled = yes
    listen_ip = 0.0.0.0
    listen_port = 4242

  # Enlace TCP hacia el Servidor Reticulum Central de CIPRO Panamá
  [[CIPRO Panama Mesh Hub]]
    type = TCPClientInterface
    enabled = yes
    target_host = rns.cipropanama.org
    target_port = 4242
